# Generated by Django 4.2.2 on 2023-07-10 22:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_cookmethod_fillingness_flavour_texture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepnumber', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('steptext', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Pantry',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='name',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step1',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step3',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step4',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step5',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='in_fridge',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(choices=[('S', 'Snap'), ('F', 'Fast'), ('R', 'Regular'), ('L', 'Long'), ('O', 'Overnight')], max_length=1),
        ),
        migrations.AddField(
            model_name='recipesteps',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredientcategory'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
