# Generated by Django 4.2.2 on 2023-08-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_recipeingredient_r'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='flavour_category_a',
            new_name='flavour_category',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='r',
        ),
    ]
