# Generated by Django 4.2.2 on 2023-06-24 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_unit_remove_recipe_steps_recipe_step1_recipe_step2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient'),
        ),
        migrations.DeleteModel(
            name='RecipeIngredients',
        ),
    ]
