# Generated by Django 4.2.2 on 2023-08-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_rename_stepnumber_recipesteps_step_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeSteps',
        ),
    ]
