# Generated by Django 4.2.2 on 2023-08-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_rename_flavour_category_a_recipe_flavour_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='step_1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step_4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='step_5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
